services:
  - type: web
    name: marisas-web-proxy
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: marisas-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: marisas-db
    plan: free